user-management/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace user_management.ViewModels
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Username is required")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; }    
    }
}

user-management/Controllers/ForgotPasswordController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using user_management.Data;
using user_management.Models;
using user_management.ViewModels;

namespace user_management.Controllers
{
    [AllowAnonymous]
    public class ForgotPasswordController : Controller
    {
        
        private readonly AppDbContext _context;
        private readonly PasswordHasher<User> _passwordHasher;
        public ForgotPasswordController(AppDbContext context, PasswordHasher<User> passwordHasher)
        {
           _context = context;
           _passwordHasher = passwordHasher;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _context.Users.SingleOrDefault(u => u.Email == model.Email);
                if (user != null)
                {

                    if (model.NewPassword == model.ConfirmPassword)
                    {
                            user.Password = _passwordHasher.HashPassword(user, model.NewPassword);
                            _context.Update(user);
                            await _context.SaveChangesAsync();
                            TempData["Message"] = "Password has been reset successfully.";
                            return RedirectToAction("Index", "Login");
                    }
                    else
                    {
                       ModelState.AddModelError(string.Empty, "New Password and Confirm Password do not match.");
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Email not found.");
                }
                
            }
            
            return View(model);
        }
    }
}

user-management/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using user_management.Data;
using user_management.Models;
using user_management.ViewModels;

namespace user_management.Controllers
{
    public class LoginController : Controller
    {
        private readonly AppDbContext _context;
        private readonly PasswordHasher<User> _passwordHasher;


        public LoginController(AppDbContext context)
        {
            _context = context;
            _passwordHasher = new PasswordHasher<User>();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _context.Users.SingleOrDefault(u => u.Username == model.Username);
                if (user != null)
                {
                    var result = _passwordHasher.VerifyHashedPassword(user, user.Password, model.Password);
                    if (result == PasswordVerificationResult.Success)
                    {
                        // Authentication successful
                        var claims = new List<Claim>
                        {   new Claim(ClaimTypes.Name, user.Username),
                            new Claim(ClaimTypes.NameIdentifier, user.Id.ToString())
                        };

                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                        await HttpContext.SignInAsync(
                            CookieAuthenticationDefaults.AuthenticationScheme,
                            new ClaimsPrincipal(claimsIdentity)
                        );

                        return RedirectToAction("Index", "Home");
                    }
                }
                ModelState.AddModelError(string.Empty, "Invalid Username or password.");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Login");
        }

    }
}

user-management/Views/Login/Index.cshtml
@using user_management.ViewModels
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model LoginViewModel

<h2>Login</h2>

<form asp-action="Index" method="post" class="col-12 col-sm-8 col-md-6 col-lg-4">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @if (TempData["Message"] != null)
    {
        <div class="alert alert-success mt-2">@TempData["Message"]</div>
    }
    <div class="form-group">
        <label asp-for="Username"></label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Password"></label>
        <input asp-for="Password" type="password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div  class="d-flex flex-row form-group">
        <div class="d-flex align-items-center">
            <button type="submit" class="btn btn-primary">Login</button>
        </div>
        <div class="ms-2 d-flex flex-column align-items-center">
            <p class="mb-0"><a asp-action="Index" asp-controller="ForgotPassword">Forgot Password?</a></p>
            <p class="mb-0">New User?<a asp-action="Index" asp-controller="Register" class="ms-2">Sign Up</a></p>
        </div>
        
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}